# Generated by Django 4.0.4 on 2022-05-23 19:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichasProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(blank=True, max_length=100, null=True)),
                ('alcance', models.CharField(blank=True, max_length=100, null=True)),
                ('flujo', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fichas_procesos',
                'managed': False,
            },
        ),

    ]
