# Generated by Django 4.0.4 on 2022-05-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0002_fichasprocesos_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': False},
        ),
    ]
