# Generated by Django 4.0.4 on 2022-05-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0003_alter_djangoadminlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichasprocesos',
            options={'managed': True},
        ),
    ]
