# Generated by Django 4.0.4 on 2022-06-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0004_alter_fichasprocesos_options'),
    ]

    operations = [
                migrations.AlterField(
            model_name='fichasprocesos',
            name='flujo',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles'),
        ),
    ]
