# Generated by Django 4.0.4 on 2022-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0005_fichasprocesos_clasificación_general_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macroprocesos',
            fields=[
                ('id_macroproceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_macroproceso', models.CharField(blank=True, max_length=100, null=True)),
                ('procesos_hijo', models.CharField(blank=True, max_length=100, null=True)),
                ('flujo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'macroprocesos',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='subprocesos',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='fichasprocesos',
            name='subprocesos',
            field=models.ManyToManyField(related_name='+', to='testdb_p1.subprocesos'),
        ),
        migrations.AddField(
            model_name='fichasprocesos',
            name='macroproceso_padre',
            field=models.ForeignKey(blank=True, db_column='macroproceso_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testdb_p1.macroprocesos'),
        ),
    ]
