# Generated by Django 4.0.4 on 2022-06-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0006_macroprocesos_alter_subprocesos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprocesos',
            name='nombre_proceso',
        ),
        migrations.AddField(
            model_name='subprocesos',
            name='proceso_padre',
            field=models.ForeignKey(blank=True, db_column='proceso_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testdb_p1.fichasprocesos'),
        ),
        migrations.AlterField(
            model_name='macroprocesos',
            name='procesos_hijo',
            field=models.ForeignKey(blank=True, db_column='proceso_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testdb_p1.fichasprocesos'),
        ),
    ]
