# Generated by Django 4.0.4 on 2022-06-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb_p1', '0007_remove_subprocesos_nombre_proceso_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='fichasprocesos',
            name='subprocesos',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='testdb_p1.subprocesos'),
        ),
    ]
